LIHPC-Computational-Geometry/honeycomb

- .gitignore
- Cargo.toml
- honeycomb-core/src/twomap.rs
- honeycomb-render/Cargo.toml
- honeycomb-render/examples/render_default_no_aa.rs
- honeycomb-render/examples/render_default_smaa1x.rs
- honeycomb-render/examples/render_splitsquaremap.rs
- honeycomb-render/examples/render_squaremap.rs
- honeycomb-render/src/camera.rs
- honeycomb-render/src/handle.rs
- honeycomb-render/src/lib.rs
- honeycomb-render/src/runner.rs
- honeycomb-render/src/shader2.wgsl
- honeycomb-render/src/shader_data.rs
- honeycomb-render/src/state.rs
Add a new member to the workspace: `honeycomb-render`. This crate implements all that is needed to visualize the structure provided by `honeycomb-core`: `TwoMap`.
To-do:
...
> feat: implement a 2D combinatorial map visualizer

- CHANGELOG.md
- honeycomb-core/src/lib.rs
- honeycomb-core/src/orbits.rs
- honeycomb-core/src/twomap.rs
Implement a generic orbit structure that can be used for consistent, standardized cell computation. The algorithm used is detailed in the documentation.
The TwoMap implementation is left unchanged at the moment since replacing its code would probably lead to breaking changes. 
To do:
...
...
> feat: implement an orbit structure for more efficient geometry computations

- CHANGELOG.md
- honeycomb-core/src/dart.rs
- honeycomb-core/src/orbits.rs
- honeycomb-core/src/twomap.rs
- honeycomb-render/examples/render_default_no_aa.rs
- honeycomb-render/examples/render_default_smaa1x.rs
- honeycomb-render/examples/render_splitsquaremap.rs
- honeycomb-render/examples/render_squaremap.rs
- honeycomb-render/src/handle.rs
- honeycomb-render/src/runner.rs
- honeycomb-render/src/state.rs
- honeycomb-utils/benches/core/cmap2/editing.rs
- honeycomb-utils/benches/core/cmap2/reading.rs
- honeycomb-utils/benches/core/cmap2/sewing.rs
- honeycomb-utils/benches/splitsquaremap/init.rs
- honeycomb-utils/benches/splitsquaremap/shift.rs
- honeycomb-utils/benches/squaremap/init.rs
- honeycomb-utils/benches/squaremap/shift.rs
- honeycomb-utils/benches/squaremap/split.rs
- honeycomb-utils/examples/memory_usage.rs
- honeycomb-utils/src/generation.rs
Remove the marks built-in the `DartData` structure. This results in many function / structure signature changes, most notably:
- `Cmap2`
- `Orbit2`
- Both `honeycomb-utils::generation` functions
- `CMap2RenderHandle` in `honeycomb-render`
...
...
> refactor: remove builtin marks

- CHANGELOG.md
- README.md
- honeycomb-core/src/cells/attributes.rs
- honeycomb-core/src/cells/mod.rs
- honeycomb-core/src/lib.rs
- honeycomb-core/src/spatial_repr/vertex.rs
Add two traits: ~`AttributeLogic`~ `AttributeUpdate` and ~`AttributeSupport`~ `AttributeBind`. These will be used in order to introduce attribute genericity in the map implementation. 
...
...
> feat: implement generic attribute traits

- honeycomb-core/src/cells/attribute_collections.rs
- honeycomb-core/src/cells/attributes.rs
- honeycomb-core/src/cells/mod.rs
- honeycomb-core/src/lib.rs
Add two basic storage structures for generic attributes: `AttrSparseVec` and `AttrCompactVec`. Their interfaces are very similar; The naming logic is as follows for access methods:
- `get`/`get_mut`: getter; Because of differences in internal storage, the return type is different between the two structure.
- `set`: setter 
- `insert`: setter that fails if there is already a value associated with the specified ID
- `replace`: setter that fails if there is no value associated with the specified ID
- `remove`: get a value & remove it from the storage. Returns `None` if no value is found for the given ID.
Additionally, all these methods will fail if the specified index:
- lands out of bounds
- fails to convert to `usize` (see `ToPrimitive` …
> feat: implement custom generic containers for our attribute system

- .github/workflows/coverage.yml
- .github/workflows/rust-test.yml
- .gitignore
- README.md
Add a new workflow to compute the test coverage of Rust code. The data is compiled into an `lcov` file & uploaded to codecov for hosting.
...
...
...
> ci: add test coverage computation & upload

- CHANGELOG.md
Add missing content from the attribute/index rework PRs to the changelog
> chore: update changelog with CMap2 rework content

- honeycomb-core/src/twomap.rs
add a new quickstart example for the `CMap2` structure, both as a doc example and as a test.
After looking into it, it seems that there are a few requirements for doctests to be included in coverage computations:
- use the nightly toolchain to add `-Z unstable-options --persist-doctests` to `RUSTDOCFLAGS`
- get the profiling data of the additional binaries generated 
For now, copy-pasting the example/test to a test/example will do.
> test: add back a new cmap2 example/test

- honeycomb-core/src/cells/orbits.rs
- honeycomb-core/src/twomap.rs
small adjustments for consistency purposes:
- change the `n_darts` method to be more intuitive
- remove the `set_beta` method & gate the `set_betas` method behind the `utils` feature
> refactor!: adjust twomap api

- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/mod.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cells/collections.rs
- honeycomb-core/src/cells/mod.rs
- honeycomb-core/src/cells/orbits.rs
- honeycomb-core/src/lib.rs
- honeycomb-core/src/spatial_repr/coords.rs
- honeycomb-core/src/spatial_repr/mod.rs
- honeycomb-core/src/spatial_repr/vector.rs
- honeycomb-core/src/spatial_repr/vertex.rs
- honeycomb-core/src/twomap.rs
- honeycomb-core/src/utils/generation.rs
- honeycomb-core/src/utils/mod.rs
Go through all the Rust doc of `honeycomb-core` to update entries & fix miscellaneous stuff. Also add `#![warn(clippy::pedantic)]` over the core crate, with some exceptions to work through later.
> doc: update public items' documentation entries

- .github/workflows/coverage.yml
- CHANGELOG.md
- Cargo.toml
- honeycomb-benches/Cargo.toml
- honeycomb-core/Cargo.toml
- honeycomb-examples/Cargo.toml
- honeycomb-render/Cargo.toml
Collection of small changes before the `0.2.0` release:
- bump package versions
- add project information to the manifests for an eventual publish on crates.io
- update the changelog file
- exclude `honeycomb-render` from the coverage report
> chore: update changelog and manifests

- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cells/orbits.rs
- honeycomb-core/src/lib.rs
- honeycomb-core/src/spatial_repr/coords.rs
- honeycomb-core/src/spatial_repr/vector.rs
- honeycomb-core/src/spatial_repr/vertex.rs
- honeycomb-core/src/twomap.rs
- honeycomb-core/src/utils/generation.rs
Remove specific lints that were previously allowed & fix warnings accordingly
> chore: process clippy lints that were previously allowed

- honeycomb-examples/Cargo.toml
- honeycomb-examples/examples/render/squaremap_shift.rs
- honeycomb-examples/examples/render/squaremap_split_diff.rs
- honeycomb-examples/examples/render/squaremap_split_some.rs
- honeycomb-examples/src/lib.rs
- honeycomb-guide/src/index.md
- honeycomb-guide/src/project-structure/honeycomb-examples.md
Add three new examples: 
- `render_squaremap_shift`
- `render_squaremap_split_diff`
- `render_squaremap_split_some`
All of these are based on the eponymous benchmarks. The shifting one only shifts inner vertices of the grid. Also, these examples will print some timing information at execution; There's no reason for it other than "it's cool".
> feat: add more examples based on benchmarks

- honeycomb-render/src/camera.rs
- honeycomb-render/src/runner.rs
- honeycomb-render/src/state.rs
Add a 240FPS hardcap on FPS of the rendering tool. While this does not de-correlates input speed from machine performance, the cap is very easily reached so the effect is almost the same.
> fix: add a hardcap to frames rendered per second of the visualizer

- honeycomb-core/src/twomap.rs
- honeycomb-render/src/handle.rs
Fix the following unwanted behaviors:
- `i_sew` executing instead of panicking when no associated attributes are defined on the given darts
- skip over rendering darts for faces that have one or less vertex
> fix: address various unwanted behaviors

- honeycomb-benches/benches/core/cmap2/editing.rs
- honeycomb-benches/benches/core/cmap2/reading.rs
- honeycomb-benches/benches/core/cmap2/sewing.rs
- honeycomb-benches/benches/splitsquaremap/init.rs
- honeycomb-benches/benches/splitsquaremap/shift.rs
- honeycomb-benches/benches/squaremap/init.rs
- honeycomb-benches/benches/squaremap/shift.rs
- honeycomb-benches/benches/squaremap/split.rs
- honeycomb-core/src/utils/generation.rs
- honeycomb-core/src/utils/mod.rs
- honeycomb-examples/Cargo.toml
- honeycomb-examples/examples/memory_usage/compute.rs
- honeycomb-examples/examples/render/splitsquaremap.rs
- honeycomb-examples/examples/render/squaremap.rs
- honeycomb-examples/examples/render/squaremap_parameterized.rs
- honeycomb-examples/examples/render/squaremap_shift.rs
- honeycomb-examples/examples/render/squaremap_split_diff.rs
- honeycomb-examples/examples/render/squaremap_split_some.rs
- implement a builder structure `GridBuilder` to generate maps representing custom grids
- mark previous generation methods as deprecated and redirect the user to an alternative
> feat: add control over grid generation using a builder struct

- CHANGELOG.md
- honeycomb-examples/examples/render/squaremap_shift.rs
- honeycomb-render/src/handle.rs
- honeycomb-render/src/representations/intermediates.rs
- honeycomb-render/src/runner.rs
- honeycomb-render/src/shader_data.rs
- honeycomb-render/src/shaders/shader2.wgsl
- honeycomb-render/src/state.rs
- update the rendering code to 
- draw proper arrows instead of triangles
- draw beta2 function as diamonds
- add an option to automatically scale arrow thickness/head size according to length
- add a binding to the F1 key to close the render window
> refactor: update render code

- .github/workflows/doc.yml
- Cargo.toml
- honeycomb-core/Cargo.toml
- honeycomb-core/build.rs
- honeycomb-core/src/lib.rs
- honeycomb-core/src/utils/generation.rs
- honeycomb-core/src/utils/mod.rs
write a custom `build.rs` script for `honeycomb-core` that allow developers to use `nightly`, `beta`, `stable` attributes in `cfg` predicates in order to generate code depending on the used toolchain. It is currently only used to enable the `doc_auto_cfg`feature when generating documentation.
> doc: enable nightly feature `doc_auto_cfg` for doc generation

- CHANGELOG.md
- honeycomb-benches/benches/splitsquaremap/shift.rs
- honeycomb-benches/benches/squaremap/shift.rs
- honeycomb-core/src/cmap2/embed.rs
- honeycomb-core/src/cmap2/structure.rs
- honeycomb-core/src/cmap2/tests.rs
- honeycomb-core/src/spatial_repr/coords.rs
- honeycomb-core/src/spatial_repr/vector.rs
- honeycomb-examples/examples/render/squaremap_shift.rs
- honeycomb-render/src/handle.rs
Change the return type of:
- `CMap2::vertex` to not panic if the specified vertex is not defined (return an error instead)
- `Vector2::normal_dir` to not panic if the method is called on a null vector (return the result of the `Vector2::unit_dir` method, which was previously unwraped internally)
The rest of the changes are accomodations for the new return types.
> refactor!: update various return types for better consistency

- .github/workflows/rust-test.yml
- CHANGELOG.md
- honeycomb-benches/Cargo.toml
- honeycomb-benches/benches/core/cmap2/editing.rs
- honeycomb-benches/benches/core/cmap2/reading.rs
- honeycomb-benches/benches/core/cmap2/sewing.rs
- honeycomb-benches/benches/splitsquaremap/init.rs
- honeycomb-benches/benches/splitsquaremap/shift.rs
- honeycomb-benches/benches/squaremap/init.rs
- honeycomb-benches/benches/squaremap/shift.rs
- honeycomb-benches/benches/squaremap/split.rs
- honeycomb-benches/src/lib.rs
- honeycomb-core/Cargo.toml
- honeycomb-core/src/cells/orbits.rs
- honeycomb-core/src/cmap2/structure.rs
- honeycomb-core/src/cmap2/tests.rs
- honeycomb-core/src/common.rs
- honeycomb-core/src/lib.rs
- honeycomb-core/src/spatial_repr/coords.rs
- honeycomb-core/src/spatial_repr/vector.rs
- honeycomb-core/src/spatial_repr/vertex.rs
- honeycomb-core/src/utils/generation.rs
- honeycomb-examples/examples/memory_usage/compute.rs
- honeycomb-examples/examples/render/squaremap_shift.rs
- honeycomb-examples/examples/render/squaremap_split_diff.rs
- honeycomb-examples/examples/render/squaremap_split_some.rs
- remove  the manual `CoordsFloat` implementation for `f32` and `f64` in favor of a generic impl block; Now, all type implementing traits required by `CoordsFloat` will automatically implement `CoordsFloat`
- remove `FloatType` from the public API & rename the `single_precision` feature to `_single_precision`; `FloatType` is now only used in tests & benchmarks
> refactor!: update float genericity code

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/doc.yml
- .github/workflows/rust-test.yml
- honeycomb-core/Cargo.toml
remove the `_single_precision` feature from the core crate & update the CI to automatically enable all features.
> chore!: remove sp feature & update CI

- examples/examples/render/squaremap.rs
- honeycomb-core/src/cmap2/advanced_ops.rs
- honeycomb-core/src/cmap2/basic_ops.rs
- honeycomb-core/src/cmap2/mod.rs
- honeycomb-core/src/cmap2/tests.rs
Implement a new method, `CMap2::split_edge`, that split an existing edges into two, giving optional control over where the new intermediary vertex is placed.
> feat(honeycomb-core): add `CMap2::split_edge` for future algorithm implementations

- honeycomb-render/src/state/camera.rs
- honeycomb-render/src/state/gfx.rs
update the camera uniform buffer to take into account the aspect ratio in the matrix view/projection transform. This solves the issue of deformation, but does not handle resolution upscaling when the window size grows.
Before:
After:
> fix(render): update aspect ratio to prevent deformation of the rendered map

- honeycomb-core/src/cmap2/structure.rs
- honeycomb-core/src/cmapbuilder/grid/building_routines.rs
- honeycomb-core/src/cmapbuilder/grid/descriptor.rs
- honeycomb-core/src/cmapbuilder/io/mod.rs
- honeycomb-core/src/cmapbuilder/structure.rs
- honeycomb-core/src/utils/generation.rs
- honeycomb-core/src/utils/mod.rs
Mark previous constructors as deprecated since `CMapBuilder` covers all of their features.
> refactor(core): deprecate old constructors

- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/cmapbuilder/grid/descriptor.rs
- honeycomb-core/src/common.rs
- honeycomb-core/src/lib.rs
> doc(core): complete `AttrStorageManager` entries & fix broken links

- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/attributes/tests.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cmap2/basic_ops.rs
- honeycomb-core/src/cmap2/embed.rs
- honeycomb-core/src/cmap2/structure.rs
- honeycomb-core/src/lib.rs
- new trait `UnknownAttributeStorage` which is attribute-agnostic, i.e. isn't defined using `A: AttributeBind`
- move some members of `AttributeStorage` to the new trait
- add index-based `merge` and `split` routines to the new trait in order to process those operations without downcasting the entire storage object
> feat!(core): add `UnknownAttributeStorage` trait for attribute-agnostic methods

- Cargo.toml
- honeycomb-core/Cargo.toml
- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/attributes/traits.rs
- title
- implement new methods to handle manager-wide updates of attribute collections
- closes #93 
Note: It looks like `downcast-rs` isn't used, but if you remove the `Downcast` trait from `UnknownAttributeStorage`, the code won't compile.
> replace `Any` by `UnknownAttributeStorage` to handle collections in attribute manager

- honeycomb-core/src/cmap2/basic_ops.rs
this was an oversight; it led to OOB accesses when using `sew` methods on newly added darts
> fix(core): extend generic attribute storages when adding darts

- honeycomb-render/src/handle.rs
this cover crashes in case at least one vertex of a face is on its center of gravity
> fix(render): add condition over shrink dir to prevent some crashes

- honeycomb-kernels/src/grisubal/kernel.rs
there are two fixes in this PR:
- a copy-paste typo where a coordinate along X was read instead of along Y - 84ffa9dd3381b0eab19cbbee080b31e2b9ac34bd
- missing topology operations in the last step of the algorithm - 44493b986ffcd79611473b626adb26ae2d09a9aa
this fixes issues mentioned in #120
> fix(kernels): correct grisubal algorithm logic

- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cells/orbits.rs
- honeycomb-core/src/cmap2/basic_ops.rs
- honeycomb-core/src/cmap2/embed.rs
- honeycomb-core/src/cmap2/structure.rs
- honeycomb-core/src/cmapbuilder/io/mod.rs
- honeycomb-core/src/spatial_repr/vertex.rs
fixes related to this new lint: https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation
> fix: indent lists in doc correctly to comply with clippy

- honeycomb-core/src/cmap2/advanced_ops.rs
- honeycomb-core/src/cmap2/tests.rs
Add a new method to `CMap2` to split a single edge into multiple segments, the number & poisiton of new vertices being given by an iterator over relative positions passed as arguments.
> feat(core): add `splitn_edge` method to `CMap2`

- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/cmap2/embed.rs
Add a method that allows removing a given storage from the manager entirely. This will be useful for the `grisubal` implementation (see #110), more specifically to remove the attribute used to model clipping regions.
> feat(core): add `remove_storage` method to `AttrStorageManager`

- examples/examples/kernels/grisubal.rs
- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/model.rs
- user-guide/src/project-structure/kernel-grisubal.md
This PR modify step 1 and step 2 of the algorithm to insert a new step in between. This step ensures correct vertex insertion even if a single edge is intersected multiple times on both of its sides.
As a side note, the `grisubal` example is now executed on the input file passed as argument: 
```
cargo run  --example grisubal -- path/to/file.vtk
```
> feat(kernels): add a dedicated intersection insertion step

- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/model.rs
Using a suggestion from @franck-ledoux; by waiting until the final step & using the `splitn_edge` method, we can avoid having random disconnected darts as PoIs in-between steps of the algorithm.
> refactor(kernels): insert PoIs using `splitn_edge` in final step of grisubal

- honeycomb-kernels/src/grisubal/grid.rs
- honeycomb-kernels/src/grisubal/kernel.rs
not having buffer cells created issues if a single point landed on upper boundaries of the box
there still are issues for capturing such geometries, but this prevents a direct crash
> refactor(kernels): add buffer cells to the overlapping grid in grisubal

- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/model.rs
- honeycomb-kernels/src/lib.rs
If a PoI is located exactly on the grid, it should be captured by intersection. To prevent duplicating vertices, we can remove the vertex's PoI status & capture the vertex using the regular intersection case.
> refactor(kernels): ignore points of interest landing exactly on the grid

- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/tests.rs
add basic tests for capturing steps of the algorithm
I want to add more coverage outside of the main steps in a separate PR after #138 is merged
> test(kernels::grisubal): add coverage using basic geometries

- examples/examples/kernels/grisubal.rs
- honeycomb-kernels/src/grisubal/clip.rs
- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/model.rs
changes can be tested using the `grisubal` example; `<CLIP>` should be `left` or `right`, no args or anything else will default to no clipping.
```
cargo run --example grisubal <VTKFILE> <CLIP>
```
- implement the clipping step, for both side of the captured geometry
- remove the `Clip::All` (follow up of a discussion with @franck-ledoux)
The clipping step can catch orientation inconsistency for geometries with "holes" & open geometries: if requirements are verified, it should not be possible to reach the other side of the boundary without crossing it in a search algorithm. Since the first substep of clipping is a coloring algorithm, we can verify the requirements at the same time.
> feat(kernel::grisubal): implement post-processing clip operation

- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/model.rs
- honeycomb-kernels/src/grisubal/tests.rs
- honeycomb-kernels/src/lib.rs
this change allows us to drop one assumption about the input geometry: it can now be defined in any range of X/Y values instead of in a strictly positive domain. A ""
> feat(kernel::grisubal): add support for non-null autocomputed origin

- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/model.rs
- honeycomb-kernels/src/grisubal/tests.rs
There were two mistakes in the `man_dist > 1` branch:
- ranges used to build the subgrid cell list were both one element short
-  top/down intersections were computed using the left/right macros instead of the correct ones
with this PR, all correctly oriented 2D shapes hosted [here](https://github.com/claireroche/Geometries) and [here](https://github.com/imrn99/meshing-samples) yield a correct result through `grisubal`
> fix(kernel::grisubal): correct range & macro calls for `man_dist > 1` intersection case

- Cargo.toml
this prevents packing debug info in release builds (which has a great cost when using the render tool)
> chore: add new profile dedicated to profiling (e.g. `perf`, flamegraphes, ...)

- .github/workflows/coverage.yml
- Cargo.toml
- honeycomb/Cargo.toml
- honeycomb/src/build.rs
- honeycomb/src/lib.rs
This PR adds a new crate: `honeycomb`. It is only made up of re-exports from the core, kernels and render crates. The goal is to provide a single dependency for users in order to (a) simplify usage, (b) avoid dependency issues where the user disable features of a crate only for another crate to enable those back.
All items of the respective core, kernels & render crate are accessible through re-exports; Additionally, a `prelude` module is defined with commonly used items.
Ideally, this crate can be published with `1.0.0`; I just need to try and get the `honeycomb` package name from crates.io since the current project using it looks dead.
> feat: add a main crate to provide a clean user API

- honeycomb-core/src/cmap/dim2/orbits.rs
remove this method since it's unused; I don't think keeping it for users is a good idea since it is pretty costly
> refactor!(core): remove `Orbit2::is_isolated`

- honeycomb-core/src/cmap/dim2/io.rs
vertex list of each face was computed using `Orbit2::Face`; This was incorrect since this orbit is defined by a BFS using both beta 0 and beta 1.
Points should be ordered sequentially for the VTK cells used to serialize maps, so I replaced the predefined orbit with a custom one which uses a single beta function to cycle through the vertices.
> fix(core): correct face computation in serializing code

- honeycomb-core/src/cmap/dim2/utils.rs
- honeycomb-kernels/src/grisubal/clip.rs
The method was removed before, but I now have a use case in the last phase of the clipping routine of `grisubal`.
> feat(core): add utility method `set_beta` to `CMap2`

- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/attributes/tests.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cmap/dim2/orbits.rs
- honeycomb-core/src/geometry/vertex.rs
- honeycomb-kernels/src/grisubal/model.rs
- remove arbitrary lifetime from `OrbitPolicy`
- replace `AttributeBind::binds_to()` with a const `OrbitPolicy`
I don't think we need runtime-valued orbit policy, & this simplifies the struct
> refactor!(core): remove lifetime from `OrbitPolicy` & update `AttributeBind`

- benches/benches/core/cmap2/basic_ops.rs
- honeycomb-core/src/attributes/tests.rs
- honeycomb-core/src/cmap/common.rs
- honeycomb-core/src/cmap/dim2/advanced_ops.rs
- honeycomb-core/src/cmap/dim2/embed.rs
- honeycomb-core/src/cmap/dim2/orbits.rs
- honeycomb-core/src/cmap/dim2/structure.rs
- honeycomb-core/src/cmap/dim2/tests.rs
- honeycomb-core/src/cmap/mod.rs
- honeycomb-core/src/prelude.rs
- honeycomb-kernels/src/grisubal/tests.rs
- honeycomb/src/lib.rs
This enum had a single variant: `CMapError::UndefinedVertex`. Removing the error and replacing `Result`s with `Option`s simplifies the code and makes the vertex/attribute metho signatures consistent. 
important changes are in the `honeycomb-core/src/cmap/dim2/embed.rs` file
> refactor!(core): remove `CMapError`

- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/mod.rs
- honeycomb-core/src/attributes/tests.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cmap/dim2/advanced_ops.rs
- honeycomb-core/src/cmap/dim2/link_and_sew.rs
- honeycomb-core/src/cmap/dim2/tests.rs
- honeycomb-core/src/geometry/vertex.rs
- honeycomb-kernels/src/grisubal/model.rs
- sew methods now behave like link methods even if there are no attribute defined (instead of panicking)
- update `UnknownAttributeStorage` implementations to print warnings instead of panick when attributes are missing
- replace `AttributeUpdate::merge_undefined` with two distinct functions depending if there's one or no attribute available
The PR has mixed content, the changes I started required more and more stuff to be changed as a consequence
> refactor(core): replace attribute-related panics with warnings

- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/attributes/tests.rs
replace some `expect` calls from `AttrStorageManager` methods with warnings. 
these methods already returned `Option`s, so the only downside to this is that a `None` return can be both due to missing data or missing storage
> refactor!(core): remove panics from manager storage accesses

- honeycomb-kernels/src/lib.rs
- honeycomb-kernels/src/triangulation/ear_clipping.rs
- honeycomb-kernels/src/triangulation/fan.rs
- honeycomb-kernels/src/triangulation/mod.rs
- honeycomb-kernels/src/triangulation/tests.rs
- honeycomb/src/lib.rs
Implement two polygon triangulation methods:
- ear clipping, which works on all polygons with no hole
- fanning, which only works on a subset of polygons; there is a generic implementation of this method and one dedicated to convex polygons
> feat(kernels): implement polygon triangulation routines

- honeycomb-core/src/cmap/dim2/advanced_ops.rs
- honeycomb-core/src/cmap/dim2/tests.rs
- honeycomb-kernels/src/grisubal/kernel.rs
both methods now take a slice of dart IDs to use as new segments components. both methods check if:
- the number of darts is consistent
- each dart is free
- each dart is non-null
> refactor!(core): change `split_edge` & `splitn_edge` to use preallocated darts

- honeycomb-core/src/cmap/dim2/advanced_ops.rs
- honeycomb-core/src/cmap/dim2/tests.rs
- honeycomb-kernels/src/grisubal/kernel.rs
All variants of the edge-splitting op now return a boolean:
- `true` if the edge was correctly split
- `false` if it could not be split, and is left unchanged
Note that:
- the `splitn_edge` did not need to return a vector of dart identifiers, we can find those after the op by using beta 1
- the returned boolean gives an actual information to the user about the completion of the op. the user can then choose to retry or abort as needed
> refactor!(core): unify edge splits method error policy

- Cargo.toml
- honeycomb-core/Cargo.toml
- honeycomb-core/src/cmap/builder/grid/descriptor.rs
- honeycomb-core/src/cmap/builder/grid/tests.rs
- honeycomb-core/src/cmap/builder/io/mod.rs
- honeycomb-core/src/cmap/builder/structure.rs
- honeycomb-core/src/geometry/mod.rs
- honeycomb-kernels/Cargo.toml
- honeycomb-kernels/src/grisubal/clip.rs
- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/model.rs
- honeycomb-kernels/src/triangulation/ear_clipping.rs
- honeycomb-kernels/src/triangulation/fan.rs
- honeycomb-kernels/src/triangulation/mod.rs
- add `thiserror` as a dependency, and use it for `BuilderError`, `GrisubalError` and `TriangulateError`
- rename some variants for consistency 
- shorten a bunch of error messages
- replace most (all?) `String`contained in enum variants by `&'static str`
I think this, along with #188, closes #175
> refactor!: cleanup error enums

- benches/src/grisubal.rs
- examples/examples/kernels/grisubal.rs
- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/cmap/builder/grid/descriptor.rs
- honeycomb-kernels/src/grisubal/model.rs
I'll replace those of `split_edge` methods in another PR
> refactor: replace regular prints with prints to stderr for warnings

- benches/Cargo.toml
- benches/benches/builder/grid_size.rs
- benches/benches/builder/time.rs
- benches/builder.py
- benches/src/builder.rs
add:
- a python script
- two benchmarks, one fixed size, one ver a range of grid sizes
- a binary to profile using perf / heaptrack / ...
> feat(bench): add benchmarking tools for the grid building routines

- benches/Cargo.toml
- benches/benches/core/cmap2/fetch_icells.rs
add a benchmark group dedicated to the following `CMap2` methods:
- `fetch_vertices`
- `fetch_edges`
- `fetch_faces`
I'm adding those to quantify an optim I thought of. I'll implement the optim in another PR, but we're looking at a 30% decrease of exec time in sequential; & the new impl can be parallelized once #201 lands
> feat(bench): add `fetch_...` methods benchmarks

- honeycomb-kernels/src/grisubal/kernel.rs
preallocation occurs in step 2 and step 4. note that:
- the computation done for preallocs are probably not optimal
- step 2 can be further modified to (a) make it more efficient, and (b) make step 3 independent from it
> refactor(kernels::grisubal): use prealloc methods for edge splitting

- Cargo.toml
- bevy_egui: 0.30.0 -> 0.29.0
- egui_dock: 0.14.0 -> 0.13.0
I'll figure out the fix later if needed
> fix(deps): revert some upgrades that broke the render menu

- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/tests.rs
- convert step 2 function to only cover vertex insertions
- move other components out of it to (a) clearup code, and (b) make step 3 independent from step 2. these components are:
- grouping intersection per edge intersected
- pre-allocating darts used for step 2
- computing each intersection's corresponding new dart
> refactor(kernels::grisubal): add intermediate compute before step 2

- honeycomb-kernels/src/grisubal/kernel.rs
replace a quadratic loop with a proper scan at two occurences
> refactor(kernels::grisubal): improve dart preallocation code

- honeycomb-kernels/src/grisubal/grid.rs
- honeycomb-kernels/src/grisubal/kernel.rs
- honeycomb-kernels/src/grisubal/tests.rs
there are two main changes to make it happen:
- split the main iterator in two, to compute and preallocate intersection metadata vector, allowing edition of the vector with no pushes
- rewrite the second part of the iterator to collect `(K, V)` pairs directly into the Hashmap rather than insert each manually
using the bench scripts, it seems like the performance is unchanged for now, which is a win since step 1 is now parallelizable
> refactor(kernels::grisubal): rewrite step 1 to enable parallelization

- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/tests.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cmap/error.rs
- honeycomb-core/src/prelude.rs
- honeycomb-kernels/src/grisubal/model.rs
**Associated issue**: closes #232 
- change:
- `AttributeUpdate::merge_incomplete` return type to `CMapResult<Self>`
- `AttributeUpdate::merge_from_none` return type to `CMapResult<Self>`
- add:
- `AttributeUpdate::split_from_none` fallback method
- update all affected implementation
> refactor!(core): update `AttributeUpdate` methods returns

- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/cmap/builder/grid/tests.rs
- honeycomb-core/src/cmap/dim2/orbits.rs
**Associated issue**: closes #235 
- add two new variants `OrbitPolicy::VertexLinear` & `OrbitPolicy::FaceLinear`
- handle their computation in `Orbit2`
- change `OrbitPolicy::Face` to use the beta 0 & beta 1 functions (it previously only used beta 1, which is what `OrbitPolicy::FaceLinear` does now)
> refactor!(core): add new variants to `OrbitPolicy`

- honeycomb-core/src/cmap/components/mod.rs
- honeycomb-core/src/cmap/components/orbits.rs
- honeycomb-core/src/cmap/dim2/orbits.rs
- honeycomb-core/src/cmap/mod.rs
**Associated issue**: #...
...
*OR*
**Scope**:  core / kernels / repository / ...
**Type of change**: feat / fix / doc / refactor / ...
...
...
> refactor(core): move `OrbitPolicy` to the components submodule

- honeycomb-core/src/cmap/dim2/sews/mod.rs
- honeycomb-core/src/cmap/dim2/sews/one.rs
- honeycomb-core/src/cmap/dim2/sews/two.rs
replaces #247, without the `StmError` to `CMapError` auto-coercion. from the old PR:
- Remove the regular variants and replace it with the `try_` variant. The latter has been renamed accordingly
- The behavior of the `force_` variant has not changed, but it is not a wrapper around the regular variant anymore: It ignores attribute-related failure and retry the transaction until complete
> refactor!(core): update sew variants

- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/attributes/mod.rs
- honeycomb-core/src/attributes/tests.rs
- make `AttributeStorageManager` only visible in the crate
- remove all of its `force_` variants
- comment out the rest of the unused methods
> refactor(core): remove dead code from `AttributeStorageManager`

- honeycomb-core/src/cmap/components/betas.rs
- honeycomb-core/src/cmap/dim2/tests.rs
- honeycomb-core/src/cmap/dim3/sews/one.rs
- honeycomb-core/src/cmap/dim3/tests.rs
**Type of change**: test
- add transactional alternatives to the example tests
- modify and add transactional alternatives to (un)sew tests
> test(core): add coverage for new routines

- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/routines/insert_intersecs.rs
- honeycomb-kernels/src/grisubal/routines/insert_new_edges.rs
- honeycomb-kernels/src/splits/edge_multiple.rs
- honeycomb-kernels/src/splits/edge_single.rs
- honeycomb-kernels/src/splits/mod.rs
- honeycomb-kernels/src/splits/tests.rs
**Scope**:  kernels
- rename `split_edge_no_alloc` & `splitn_edge_no_alloc` to `split_edge_transac` & `splitn_edge_transac`
- update API of both methods to accept transactions
- update `SplitEdgeError` to have a failed transaction variant
- update common internal routine to use a transaction
merge this back into #269 and finish writing the new benchmark.
> refactor!(kernels): convert `split_edge` routines to use transactions

- honeycomb-core/src/cmap/dim2/basic_ops.rs
- honeycomb-core/src/cmap/dim3/basic_ops.rs
remove the usage of `.unique()` from itertools by using dart properties to filter values. this was motivted by the fact that `.unique()` allocates a Set to perform its task, while this solution uses no additional allocation.
exec time is reduced by 3 / 30 / 8 % for cells of dimension 0 / 1 / 2
> refactor(core): improve `iter_<CELLS>` methods

- honeycomb-core/src/cmap/dim2/basic_ops.rs
**Type of change**: fix 
the condition for the while loop may never be reached in transactional contexts due to data edits that are not detected until commit time. by reverting to the usual routines used by orbits/3D, we can avoid this issue and guarantee to reach commit time.
> fix(core): replace `while` with marks in 2D ID computations

- honeycomb-render/src/app.rs
- honeycomb-render/src/capture/system.rs
- honeycomb-render/src/render/mod.rs
- honeycomb-render/src/render/scene.rs
- honeycomb-render/src/render/update.rs
**Scope**:  core / kernels / repository / ...
**Type of change**: feat / fix / doc / refactor / ...
- title 
- limit draggable render params update to click release for perf
- remove point lights (seems to drastically improve perf too)
- remove docked menu in favor of a draggable window with keybinds
- make a binary that taks a cmap file as arg?
- add `From<CMap3>` impl for `Capture`
> feat(render): use white background & unlit i-cells to improve visuals

- honeycomb-core/src/attributes/collections.rs
- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/attributes/tests.rs
- honeycomb-core/src/attributes/traits.rs
- honeycomb-core/src/cmap/dim2/embed.rs
- honeycomb-core/src/cmap/dim3/embed.rs
**Content description**: follow up of #277 
Now that the API has converged, the only methods variants we need are transactional. we can wrap them at the highest level since the user is not supposed to directly interact with attribute containers anyway. 
I will do yet another PR to rename the remaining methods from the various attribute traits since code fro the `sew` impls will be affected
> refactor(core): remove dead code from attribute items

- benches/src/cut_edges.rs
- benches/src/shift.rs
- honeycomb-kernels/src/lib.rs
- honeycomb-kernels/src/remeshing/mod.rs
- add a new `remeshing` module to the kernel crate
- move core operations of the `shift` and `cut-edges` benchmarks there
> add remeshing module w/ cut-edges routines

- benches/benches/core/cmap2/basic_ops.rs
- benches/benches/core/cmap2/constructors.rs
- benches/benches/core/cmap2/link_and_sew.rs
- benches/benches/triangulate/quads.rs
- benches/src/cut_edges.rs
- benches/src/grid_gen.rs
- benches/src/shift.rs
- examples/examples/io/read.rs
- examples/examples/render.rs
- honeycomb-core/src/attributes/tests.rs
- honeycomb-core/src/cmap/builder/structure.rs
- honeycomb-core/src/cmap/builder/tests.rs
- honeycomb-core/src/cmap/dim2/structure.rs
- honeycomb-core/src/cmap/dim2/tests.rs
- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/tests.rs
- honeycomb-kernels/src/splits/edge_multiple.rs
- honeycomb-kernels/src/splits/tests.rs
- honeycomb-kernels/src/triangulation/tests.rs
**Scope**: core with fixes in other crates
- update `CMapBuilder` internal to use a private enum that distinguishes between init methods
- remove field setters as a consequence; this also removes the "priority" requirements for the case where conflicting fields were set (e.g. a grid descriptor and a file)
- remove the `Default` and `From<GridDescriptor>` impls for `CMapBuilder`. The item is now exclusively built using non-ambiguous functions (e.g. `from_grid_descriptor`)
> refactor!(core): update the builder structure API

- honeycomb-core/src/cmap/components/orbits.rs
- honeycomb-core/src/cmap/dim2/orbits.rs
- honeycomb-core/src/cmap/dim2/tests.rs
- honeycomb-core/src/cmap/dim3/orbits.rs
- honeycomb-core/src/cmap/dim3/tests.rs
- honeycomb-core/src/cmap/mod.rs
**Scope**: core
- add a custom unfold iterator `TryFromFn` to use `?` inside the definition closure
- implement transactional orbit computations. 
Usage is slightly weird since chaining operators isn't be possible due to the closure system. The only two solutions I see for this are:
- remove lazy computations, and check whether anything is invalid before returning an iterator over values (effectively moving the `Result` out of the iterator)
- provide a functions that does what's described above, to still allow using the lazily evaluated iterator (in a for loop for example, where results can be `?`)
use this content in #298 to expose transactions in the API
> feat(core): implement transactional orbits

- honeycomb-core/src/cmap/dim2/sews/two.rs
- honeycomb-core/src/cmap/dim3/sews/three.rs
- honeycomb-core/src/cmap/dim3/sews/two.rs
- honeycomb-kernels/src/grisubal/model.rs
- honeycomb-kernels/src/remeshing/anchoring.rs
- honeycomb-kernels/src/remeshing/mod.rs
- honeycomb-kernels/src/remeshing/tests.rs
- add three new enums: `VertexAnchor`, `EdgeAnchor`, and `FaceAnchor`
- implement attribute traits for these
- ~~add tests~~ done
- set these at the end of the `grisubal` kernel
- use these to implement predicates controlling the `collapse_edge` routine
> feat(kernels): implement geometrical anchoring attributes

- honeycomb-core/src/attributes/manager.rs
- honeycomb-core/src/cmap/dim2/embed.rs
- honeycomb-core/src/cmap/dim3/embed.rs
- honeycomb-kernels/src/grisubal/mod.rs
- honeycomb-kernels/src/grisubal/routines/clip.rs
- honeycomb-kernels/src/grisubal/routines/insert_new_edges.rs
- honeycomb-kernels/src/grisubal/routines/pre_processing.rs
- honeycomb-kernels/src/remeshing/anchoring.rs
- honeycomb-kernels/src/remeshing/capture.rs
- honeycomb-kernels/src/remeshing/mod.rs
- honeycomb-kernels/src/remeshing/tests.rs
> refactor(grisubal): add anchor insertion after geometry capture

- honeycomb-render/Cargo.toml
- honeycomb-render/src/import_map.rs
- honeycomb-render/src/lib.rs
- honeycomb-render/src/render_map.rs
- honeycomb-render/src/scene/mod.rs
**Scope**: render
- add bevy items to import and render `CMap3` items
- add a main rendering function
I haven't renamed 2D items to not break things uselessly
render and grid generation both fixed; next step is fixing the shrinking logic to avoid uneven shrinks.
> feat(render): add support for `CMap3` rendering

- honeycomb-core/src/cmap/dim2/basic_ops.rs
- honeycomb-core/src/cmap/dim3/basic_ops.rs
title
To avoid potential bugs / inconsistencies, we need to clear all attributes of the removed dart too. This requires adding a new method to `UnknownAttributeStorage`, which is a breaking change
> feat(core): add transactional dart removal

- honeycomb-kernels/src/triangulation/ear_clipping.rs
**Content description**: in the ear clipping triangulation routine:
- fix the usage of new darts
- replace a `while` with a `for`; this should be less bug-prone
> fix(triangulation): read new darts correctly in ear_clip routine

- .github/workflows/build.yml
- .github/workflows/rust-test.yml
- Cargo.toml
- benches/Cargo.toml
- benches/src/cut_edges.rs
- benches/src/main.rs
- benches/src/utils.rs
**Scope**: benches
- add a `bind-threads` feature to the benchmark crate
- read number of threads used for each benchmark from env variables
- read binding policy from env variables
- add binding function and required feature checks
- temporarily disable features in CI, will re-enable when I update the CI in another PR
update the CI to enable the `bind-threads` feature by default in the `honeycomb-benches` crate
TODO:
> feat(benches): implement thread binding with `hwlocality`

- .github/workflows/build_nix.yml
- .github/workflows/spell-check.yaml
see #341 
this was an attempt at fixing the CI, but I ended up adding interesting stuff to it.
- we now build on both x86_64 and arm based macos runners
- the `fail-fast` option ensures a linux job won't be cancelled after a macos failure, or vice-versa
> chore: improve *nix CI
