LIHPC-Computational-Geometry/honeycomb

.github/ISSUE_TEMPLATE/1-bug.md, honeycomb-core/src/dart.rs, honeycomb-core/src/embed.rs, honeycomb-core/src/twomap.rs, honeycomb-guide/src/definitions/darts.md, honeycomb-guide/src/definitions/embedding.md, honeycomb-guide/src/definitions/introduction.md, honeycomb-guide/src/definitions/orbits.md
=> Fix few typos

.github/workflows/bench.yml
Rename a job & add missing  dependency
...
...
...
=> ci: fix benchmark ci on release

CHANGELOG.md, README.md, honeycomb-core/Cargo.toml, honeycomb-core/src/coords.rs, honeycomb-core/src/lib.rs, honeycomb-core/src/twomap.rs, honeycomb-guide/src/SUMMARY.md, honeycomb-guide/src/index.md, honeycomb-guide/src/project-structure/honeycomb-core.md, honeycomb-guide/src/project-structure/honeycomb-render.md, honeycomb-guide/src/project-structure/workspace.md, honeycomb-render/Cargo.toml, honeycomb-render/src/camera.rs, honeycomb-render/src/handle.rs, honeycomb-render/src/runner.rs, honeycomb-render/src/shader_data.rs, honeycomb-render/src/state.rs, honeycomb-utils/Cargo.toml
Update user guide, in-code documentation, readme and changelog before release.
... 
...
=> doc: update rustdoc, user guide & readme

.github/workflows/build.yml, README.md
Add a new workflow to test compilation of various components of the project, on various platforms
...
...
...
=> feat: add a build CI with benches, examples, libs for different OSes

.github/ISSUE_TEMPLATE/1-bug.md, .github/ISSUE_TEMPLATE/2-documentation.md, .github/ISSUE_TEMPLATE/3-enhancement.md, .github/ISSUE_TEMPLATE/8-release.md, .github/ISSUE_TEMPLATE/9-question.md, .github/pull_request_template.md, CONTRIBUTING.md, LICENSE-APACHE, LICENSE-MIT, README.md
This is a collection of  misc changes for the repository:
- simplify already existing templates & add a new one to track to-do tasks before release.
- add license information
- add a contributing guideline
=> chore: update repository templates, license, contributing

honeycomb-core/src/attributes/collections.rs, honeycomb-core/src/attributes/mod.rs, honeycomb-core/src/attributes/traits.rs, honeycomb-core/src/cells/orbits.rs, honeycomb-core/src/lib.rs, honeycomb-core/src/spatial_repr/vector.rs, honeycomb-core/src/twomap.rs
=> test: write more tests for the core crate

honeycomb-core/src/twomap.rs, honeycomb-examples/examples/memory_usage/plot.py, honeycomb-guide/src/project-structure/honeycomb-examples.md
Update:
- the `memory_usage` example code
- attribute re-insertion code in `CMap2::two_unsew`; a previously unseen case was identified
- the plotting script, to correctly parse & plot data from newly generated csv files
=> fix: update the memory usage example (both code & plot script)

CHANGELOG.md, Cargo.toml, README.md, honeycomb-benches/benches/splitsquaremap/shift.rs, honeycomb-benches/benches/squaremap/shift.rs, honeycomb-benches/benches/squaremap/split.rs, honeycomb-examples/examples/render/squaremap_shift.rs, honeycomb-examples/examples/render/squaremap_split_diff.rs, honeycomb-examples/examples/render/squaremap_split_some.rs, honeycomb-guide/src/index.md
misc updates before release `0.2.1`
=> chore: update changelog, bump versions

.github/workflows/doc.yml, honeycomb-core/src/attributes/collections.rs, honeycomb-core/src/lib.rs, honeycomb-core/src/utils/generation.rs, honeycomb-core/src/utils/mod.rs, honeycomb-guide/src/project-structure/honeycomb-core.md
remove deprecated items and update the UG to mention utilities. Also, add the `utils` feature to the doc CI.
=> refactor!: remove items marked as deprecated in `0.2.1`

CHANGELOG.md, README.md, benches/src/lib.rs, examples/src/lib.rs, honeycomb-core/src/cmap2/io.rs, honeycomb-core/src/cmap2/mod.rs, honeycomb-core/src/lib.rs, user-guide/src/index.md, user-guide/src/project-structure/honeycomb-core.md, user-guide/src/project-structure/honeycomb-examples.md
=> doc: update rustdoc & user guide

Cargo.toml
=> chore: update members & dep version

honeycomb-render/src/handle.rs
title + I added a note on the fact that my shrinking routine is technically incorrect.
=> fix(render): shrink face relatively to their original sizes

honeycomb-core/src/attributes/manager.rs, honeycomb-core/src/cmapbuilder/grid/building_routines.rs, honeycomb-core/src/cmapbuilder/io/mod.rs, honeycomb-core/src/cmapbuilder/io/tests.rs, honeycomb-core/src/cmapbuilder/structure.rs
- add support for the new storage manager struct to `CMapBuilder`; This is the last step before adding the manager to the map & wiring it up
=> feat(core): add storage manager to builder

Cargo.toml, honeycomb-core/Cargo.toml, honeycomb-core/src/attributes/manager.rs, honeycomb-core/src/attributes/traits.rs, honeycomb-core/src/cmap2/embed.rs, honeycomb-core/src/cmap2/link_and_sew.rs, honeycomb-core/src/cmap2/structure.rs, honeycomb-core/src/cmapbuilder/grid/building_routines.rs, honeycomb-core/src/cmapbuilder/io/mod.rs
This is a follow up of #96, #97, #102 and all preceding PR building up the generic attribute storage system.
closes #57
=> feat(core): add generic storage manager to `CMap2`

honeycomb-core/src/attributes/manager.rs
=> doc(core): remove mentions of `Any` from `AttrStorageManager` entry

honeycomb-core/src/attributes/tests.rs, honeycomb-core/src/cmap2/structure.rs, honeycomb-core/src/cmapbuilder/grid/building_routines.rs, honeycomb-core/src/cmapbuilder/structure.rs
- add tests over the items used to implement the generic attribute system
- fix mistakes in implementation highlighted by new tests
=> test: add coverage for new attribute-related items

CHANGELOG.md, Cargo.toml, honeycomb-core/src/attributes/traits.rs, honeycomb-core/src/cmap2/structure.rs
=> chore: bump crates' versions

Cargo.toml, honeycomb-kernels/Cargo.toml, honeycomb-kernels/src/lib.rs
=> feat(kernels): add new workspace member for algorithms implementation

honeycomb-kernels/Cargo.toml, honeycomb-kernels/src/grisubal/grid.rs, honeycomb-kernels/src/grisubal/inp.rs, honeycomb-kernels/src/grisubal/kernel.rs, honeycomb-kernels/src/grisubal/mod.rs, honeycomb-kernels/src/grisubal/tests.rs, honeycomb-kernels/src/lib.rs
This is a draft of what/how items will be used to write the first algorithm described in #110.
=> feat(kernel): add a skeleton impl of the first algorithm

honeycomb-kernels/src/grisubal/grid.rs, honeycomb-kernels/src/grisubal/inp.rs, honeycomb-kernels/src/grisubal/kernel.rs, honeycomb-kernels/src/grisubal/mod.rs, honeycomb-kernels/src/lib.rs
part of #110 
implement a few routines (bounding box computation, Manhattan distance) & adjust some signatures.
=> feat(kernels): implement pre-processing components of `grisubal`

honeycomb-kernels/src/grisubal/grid.rs, honeycomb-kernels/src/grisubal/mod.rs, honeycomb-kernels/src/lib.rs
title + fix induced warnings to pass CI
=> chore(kernels): enable `clippy::pedantic` lints for the kernel member

honeycomb-kernels/Cargo.toml, honeycomb-kernels/src/grisubal/inp.rs, honeycomb-kernels/src/grisubal/tests.rs
=> feat: implement geometry reading from vtk input

Cargo.toml, benches/benches/splitsquaremap/shift.rs, benches/benches/squaremap/shift.rs, benches/benches/squaremap/split.rs, examples/examples/io/write.rs, examples/examples/render/squaremap_shift.rs, examples/examples/render/squaremap_split_diff.rs, examples/examples/render/squaremap_split_some.rs
=> chore: fix errors introduced by `rand` update

examples/examples/kernels/grisubal.rs, honeycomb-kernels/src/grisubal/kernel.rs, honeycomb-kernels/src/grisubal/mod.rs, honeycomb-kernels/src/grisubal/model.rs, honeycomb-kernels/src/grisubal/tests.rs, honeycomb-kernels/src/lib.rs
this PR add a lot of error logic & wire all of it back to the main function; it should help identify which errors are (supposedly) handled and which are overlooked.
=> refactor(kernels::grisubal): add error handling logic across all of the module

honeycomb-core/src/cmapbuilder/grid/building_routines.rs, honeycomb-core/src/cmapbuilder/grid/descriptor.rs, honeycomb-core/src/cmapbuilder/structure.rs, honeycomb-kernels/src/grisubal/kernel.rs
Summary of the changes if needed.
=> feat: add origin offset directly to grid descriptor/builder

honeycomb-kernels/src/grisubal/grid.rs, honeycomb-kernels/src/grisubal/model.rs
Summary of the changes if needed.
=> fix(kernel::grisubal): implement edge case detection & origin shift

user-guide/src/project-structure/kernel-grisubal.md
=> doc(user-guide): update grisubal page with pre/post processing description

Cargo.toml, honeycomb-core/Cargo.toml, honeycomb-core/src/attributes/collections.rs, honeycomb-core/src/attributes/traits.rs, honeycomb-core/src/cmap/builder/io/mod.rs, honeycomb-core/src/geometry/mod.rs, honeycomb-kernels/Cargo.toml, honeycomb-kernels/src/grisubal/model.rs
- replace `num` with `num_traits` & remove its usage in the kernel crate
- remove `cfg-if` from the core crate
=> chore: minimize deps usage

CHANGELOG.md, Cargo.toml, README.md, benches/Cargo.toml, user-guide/src/index.md
- update changelog
- update usage instructions
- bump package & dependencies versions
=> chore: prepare 0.6.0 release

honeycomb-core/src/attributes/mod.rs, honeycomb-core/src/attributes/traits.rs, user-guide/src/SUMMARY.md, user-guide/src/usage/attributes.md
**Scope**:  core / repository
**Type of change**: doc
**Content description**: title
=> doc: replace attribute doctests by a user guide page

user-guide/src/SUMMARY.md, user-guide/src/usage/stm.md
- update original example
- add another example with fallible transactions
- separate the first section into `Needs` and `STM`, with more info about transactions in `STM`
=> doc: update the STM usage page

user-guide/src/usage/attributes.md, user-guide/src/usage/stm.md
**Scope**:  user guide
**Type of change**: doc
**Content description**: title
=> doc: update UG examples with new syntax

honeycomb-kernels/src/remeshing/mod.rs, honeycomb-kernels/src/remeshing/tests.rs
- implement the `swap_edge` operation (as a function) to use in a remeshing pipeline
=> feat(kernels): add `swap_edge` remeshing operation

benches/src/cut_edges.rs, benchmarks.dockerfile, honeycomb-kernels/src/remeshing/mod.rs
**Scope**: benches
**Type of change**: fix
**Content description**: see the 3 commits
this should be a rebase-merge
=> various bench fixes

CHANGELOG.md, README.md, user-guide/src/SUMMARY.md, user-guide/src/index.md, user-guide/src/kernels/dvr.md, user-guide/src/kernels/remeshing.md, user-guide/src/kernels/splits.md, user-guide/src/project-structure/published.md
**Scope**: repository
**Content description**: see commits
=> chore: prep for `0.8.0`

honeycomb-render/src/gui.rs, honeycomb-render/src/lib.rs, honeycomb-render/src/options.rs, honeycomb-render/src/render_map.rs, honeycomb-render/src/scene/mod.rs
**Scope**: render
**Content description**: 
this is not ideal since the lack of "fills" hinder the mesh visualization, but it is good for debugging and map visualization.
=> feat(render): render faces using lines

benches/src/main.rs
title
the cli option was there, but the code was left as `todo!()`
=> feat(benches): add `f32` support to `hc-bench`

honeycomb-core/src/cmap/builder/grid.rs
**Scope**: core
**Type of change**: fix
**Content description**: title
I used #310 to check the result. There still is a rendering bug tho
Merge this back into #310
=> fix(core): correct vertex values for 3D grid generation

.github/workflows/spell-check.yaml, .typos.toml, benches/benches/core/cmap2/link_and_sew.rs, user-guide/src/definitions/changeNdart.md, user-guide/src/definitions/embedding.md, user-guide/src/definitions/sew.md, user-guide/src/index.md, user-guide/src/kernels/grisubal.md, user-guide/src/project-structure/honeycomb-benches.md, user-guide/src/project-structure/others.md, user-guide/src/usage/serialization.md, user-guide/src/usage/stm.md
**Scope**: repository
- remove specific files / file paths from the CI
- ignore all `svg` files
- fix new diagnostics
With this config, `typos` has the same output in the CI and locally. All files ignored by git are ignored, and all `svg`s also are. This enables full coverage.
=> update spellcheck CI

.pre-commit-config.yaml, CONTRIBUTING.md, user-guide/src/SUMMARY.md, user-guide/src/index.md, user-guide/src/project-structure/contributing.md
**Scope**: repository
**Content description**: see commits
=> feat: add a pre-commit hook config file

honeycomb-kernels/src/remeshing/anchoring.rs, honeycomb-kernels/src/remeshing/cut.rs
**Content description**: see commits
=> feat(remeshing): add anchor support in cut edge routines

honeycomb-core/src/cmap/dim2/sews/two.rs, honeycomb-core/src/cmap/dim3/sews/two.rs, honeycomb-kernels/src/remeshing/anchoring.rs, honeycomb-kernels/src/remeshing/tests.rs
**Type of change**: test
**Content description**: see commits
=> update remeshing tests

CHANGELOG.md, Cargo.toml, README.md, honeycomb-core/src/cmap/builder/tests.rs, honeycomb/src/lib.rs, user-guide/src/index.md
=> update misc content for `0.8.1`

benches/src/cli.rs, benches/src/lib.rs, benches/src/main.rs, benches/src/remesh.rs, honeycomb-kernels/src/remeshing/collapse.rs, honeycomb-kernels/src/remeshing/cut.rs, honeycomb-kernels/src/remeshing/mod.rs, honeycomb-kernels/src/remeshing/swap.rs, honeycomb-kernels/src/remeshing/tests.rs, honeycomb-kernels/src/utils/routines.rs
**Scope**:  kernels / benches
**Content description**: title + commits
cleanup of #326 
- add parallelization and implement the backend selection
- add documentation of the pipeline in the user guide
=> implement the 2D remeshing pipeline

benches/src/remesh.rs, honeycomb-core/src/attributes/collections.rs, honeycomb-core/src/attributes/manager.rs, honeycomb-core/src/attributes/traits.rs, honeycomb-core/src/cmap/dim2/structure.rs, honeycomb-core/src/cmap/dim3/structure.rs, honeycomb/Cargo.toml
See commits
There are a few performance things to test (most notably, perf of the check of the swap operation).
I think weak scaling will be impossible to properly define, so we'll run strong scaling
=> implement parallel remeshing
